[package]
name = "iroh-util"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Utilities for iroh"

[dependencies]
cid = "0.8.4"
config = "0.13.1"
ctrlc = "3.2.2"
dirs-next = "2.0.0"
futures = "0.3.21"
humansize = "2.0.0"
rlimit = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.26.5"
temp-env = "0.3.1"
thiserror = "1.0"
toml = "0.5.9"
tracing = "0.1.34"

[dev-dependencies]
tempfile = "3.3.0"

[target.'cfg(unix)'.dev-dependencies]
nix = "0.25"
