[package]
name = "iroh-resolver"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of path resolution for iroh"

[dependencies]
async-channel = "1.7.1"
async-recursion = "1.0.0"
async-stream = "0.3.3"
async-trait = "0.1.53"
base64 = "0.13.1"
bytes = "1.1.0"
cid = "0.8.4"
fastmurmur3 = "0.1.2"
futures = "0.3.21"
iroh-metrics = { path = "../iroh-metrics", default-features = false, features = ["resolver", "gateway"] }
iroh-rpc-client = { path = "../iroh-rpc-client", default-features = false }
iroh-util = { path = "../iroh-util", default-features = false }
libipld = "0.14.0"
libp2p = { version = "0.50", default-features = false, features = ["serde"] }
multihash = "0.16.3"
num_enum = "0.5.7"
once_cell = "1.13.0"
prost = "0.11"
rand = "0.8.5"
reqwest = { version = "0.11", features = ["rustls-tls", "json"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1"
tokio = { version = "1", features = ["fs"] }
tokio-util = { version = "0.7", features = ["io"] }
tracing = "0.1.34"
trust-dns-resolver = { version = "0.22.0", features = ["tokio-runtime"] }
unsigned-varint = "0.7.1"
url = "2.2"

[dev-dependencies]
anyhow = "1"
criterion = { version = "0.4.0", features = ["async_tokio"] }
fnv = "1.0.7"
iroh-car = { path = "../iroh-car" }
iroh-rpc-types = { path = "../iroh-rpc-types", default-features = false }
iroh-store = { path = "../iroh-store", default-features = false }
proptest = "1.0.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
tempfile = "3.3.0"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "fs"] }

[build-dependencies]
prost-build = "0.11.1"

[features]
default = ["rpc-grpc", "rpc-mem"]
rpc-grpc = ["iroh-rpc-client/grpc", "iroh-metrics/rpc-grpc", "iroh-rpc-types/grpc", "iroh-store/rpc-grpc"]
rpc-mem = ["iroh-rpc-client/mem", "iroh-rpc-types/mem", "iroh-store/rpc-mem"]

[[bench]]
name = "unixfs"
harness = false
