[package]
name = "iroh-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Rust API for Iroh"

[features]
testing = ["dep:mockall"]

[dependencies]
async-stream = "0.3.3"
bytes = "1.1.0"
cid = "0.8.5"
config = "0.13.1"
futures = "0.3.21"
iroh-metrics = { path = "../iroh-metrics", default-features = false, features = ["rpc-grpc"] }
iroh-resolver = { path = "../iroh-resolver" }
iroh-rpc-client = { path = "../iroh-rpc-client" }
iroh-rpc-types = { path = "../iroh-rpc-types" }
iroh-util = { path = "../iroh-util" }
libp2p = "0.50"
mockall = { version = "0.11.2", optional = true }
relative-path = "1.7.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1" }
tracing = "0.1.34"
url = "2.2"

[dev-dependencies]
tempfile = "3.3.0"
anyhow = "1"
